server:
  port: 8002
spring:
  application:
    name: msventas
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:5000/eureka
    instance:
      hostname: localhost
