server:
  port: 8001
spring:
  freemarker:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3307/ventas
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    initialize: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  application:
    name: MsVentas
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        Type: TRACE
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost
